#pragma kernel BuildVertex
#pragma kernel BuildMesh

struct GeneratedVertex {
    int3 position;
    float3 normal;
    int4 uv0;
    int4 uv1;
};
struct GeneratedVertexLow {
    uint2 position;
    uint2 normal;
    uint2 uv0;
    uint2 uv1;
};

#define SIZE_1 32
#define SIZE_2 1024
#define SIZE_3 32768

#define EXTRA_1 34
#define EXTRA_2 1156

#define CHUNKS_1 6
#define CHUNKS_2 36
#define CHUNKS_3 216

#define BUFFER_SIZE 2122416


//
// BuildVertex
//
uint4 chunk_pos;

StructuredBuffer<int> TriangleTable;
        
StructuredBuffer<uint> VoxelBuffer;
StructuredBuffer<uint> ChunkBuffer;
StructuredBuffer<uint> MaterialBuffer;

RWStructuredBuffer<uint> ExtraCounter;
RWStructuredBuffer<uint> VertexCounter;
RWStructuredBuffer<uint2> VoxelsCounter;
RWStructuredBuffer<GeneratedVertex> VertexBuffer;

static const float lut[16] = {
    0.00, 0.10, 0.20, 0.30, 0.40, 0.45, 
    0.55, 0.60, 0.65, 0.70, 0.75,
    0.80, 0.85, 0.90, 0.95, 1.00
};

void WriteVertex(const uint offset, const float3 p, const float3 n, const int3 id, const int uv, const float4 mat) {
    GeneratedVertex vertex;
    vertex.position = (int3)round(p * 1024);
    vertex.normal = n;
    vertex.uv0 = int4(id, uv);
    vertex.uv1 = mat;
    VertexBuffer[offset] = vertex;
}

float2 ReadVoxel(const uint x, const uint y, const uint z) {
    const uint index = (x & 31) + (z & 31) * SIZE_1 + (y & 31) * SIZE_2;
    const uint offset = ChunkBuffer[(x >> 5) + (z >> 5) * CHUNKS_1 + (y >> 5) * CHUNKS_2];

    const uint densityPacked = VoxelBuffer[offset + (index >> 3)];
    const uint densityShift = (index & 7) * 4;
    const uint density = (densityPacked >> densityShift) & 0xF;

    const uint materialPacked = MaterialBuffer[offset * 2 + (index >> 2)];
    const uint materialShift = (index & 3) * 8;
    const uint material = (materialPacked >> materialShift) & 0xFF;

    return float2(lut[density], material);
}

float2 SampleVoxel(const uint3 pos) {
    const float2 vox = ReadVoxel(pos.x, pos.y, pos.z);
    return float2(vox.x, vox.y);
}

uint3 CubeVertex(const uint index) {
    // (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
    // (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)
    const bool x = index & 1;
    const bool y = index & 2;
    const bool z = index & 4;
    return uint3(x ^ y, y, z);
}

uint2 EdgeVertexPair(const uint index) {
    // (0, 1) (1, 2) (2, 3) (3, 0)
    // (4, 5) (5, 6) (6, 7) (7, 4)
    // (0, 4) (1, 5) (2, 6) (3, 7)
    const uint v1 = index & 7;
    const uint v2 = index < 8 ? ((index + 1) & 3) | (index & 4) : v1 + 4;
    return uint2(v1, v2);
}

[numthreads(2, 2, 2)]
void BuildVertex(uint3 id : SV_DispatchThreadID) {
    const uint3 vx = id + chunk_pos.xyz - uint3(1, 1, 1);
    
    uint selector = 0;
    float2 samples[8];
    uint i;
    for (i = 0; i < 8; i++) {
        samples[i] = SampleVoxel(vx + CubeVertex(i));
        selector |= (samples[i].x < 0.5) << i;
    }
    
    if (selector == 0 || selector == 0xff) return;
    
    float4 vertices[12];
    float4 materials[12];
    for (i = 0; i < 12; i++) {
        const uint2 pair = EdgeVertexPair(i);
        const float2 sample1 = samples[pair.x];
        const float2 sample2 = samples[pair.y];
        const float3 vertex1 = vx + CubeVertex(pair.x);
        const float3 vertex2 = vx + CubeVertex(pair.y);
        const float param = (0.5 - sample1.x) / (sample2.x - sample1.x);
        const float mat = sample1.x >= sample2.x ? param >= 0.75 ? sample2.y : sample1.y : param < 0.25 ? sample1.y : sample2.y;
        
        vertices[i] = float4(lerp(vertex1, vertex2, param) - chunk_pos.xyz - uint3(1, 1, 1), mat);
    }

    const uint table_index = selector * 19;
    const uint max = TriangleTable[table_index];
    
    uint index;
    if (id.x == 0  || id.y == 0  || id.z == 0 ||
        id.x == 33 || id.y == 33 || id.z == 33) {
        InterlockedAdd(ExtraCounter[0], max, index);
        index = BUFFER_SIZE - index - max;
    } else {
        InterlockedAdd(VertexCounter[0], max, index);
    }
    
    VoxelsCounter[id.x + (id.z * EXTRA_1) + (id.y * EXTRA_2)] = uint2(index, max);
    
    for (i = 0; i < 18; i+= 3) {
        const int t_index0 = TriangleTable[table_index + i + 1];
        const int t_index1 = TriangleTable[table_index + i + 2];
        const int t_index2 = TriangleTable[table_index + i + 3];
        if (t_index0 < 0) return;

        const float3 normal = normalize(
            cross(
                vertices[t_index1].xyz - vertices[t_index0].xyz,
                vertices[t_index2].xyz - vertices[t_index0].xyz
            )
        );
        // x[MatA] y[WeightA] z[MatB] w[WeightB]
        float3 mat = float3(vertices[t_index0].w, vertices[t_index1].w, vertices[t_index2].w); 
        // Material List
        const float4 mat0 = float4(materials[t_index0].xz, materials[t_index1].xz);
        const float2 mat1 = materials[t_index2].xz;

        // Vertex Weight 0
        const float4 vw00 = float4(materials[t_index0].yw, 0.0, 0.0);
        const float2 vw01 = float2(0.0, 0.0);
        
        // Vertex Weight 1
        const float4 vw10 = float4(0.0, 0.0, materials[t_index1].yw);
        const float2 vw11 = float2(0.0, 0.0);
        
        // Vertex Weight 2
        const float4 vw20 = float4(0.0, 0.0, 0.0, 0.0);
        const float2 vw21 = float2(materials[t_index2].yw);
        
        WriteVertex(index + i    , vertices[t_index0].xyz, normal, id, 0.0, float4(mat, 0.0));
        WriteVertex(index + i + 1, vertices[t_index1].xyz, normal, id, 0.0, float4(mat, 1.0));
        WriteVertex(index + i + 2, vertices[t_index2].xyz, normal, id, 0.0, float4(mat, 2.0));
    }
}

//
// BuildMesh
//
uint4 vertex_count;

StructuredBuffer<uint2> MeshCounter;
StructuredBuffer<GeneratedVertex> MeshInput;

RWStructuredBuffer<GeneratedVertexLow> MeshVertexBuffer;
RWStructuredBuffer<uint> MeshIndexBuffer;

[numthreads(64, 1, 1)]
void BuildMesh(uint3 id : SV_DispatchThreadID) {
    const uint index = id.x;
    if (index >= vertex_count.x) return;
    
    GeneratedVertex ver = MeshInput[index];
    
    float3 normal = float3(0.0, 0.0, 0.0);
    for (int x = -1; x <= 1; x++)
    for (int y = -1; y <= 1; y++)
    for (int z = -1; z <= 1; z++) {
        int2 counter = MeshCounter[x + ver.uv0.x + ((z + ver.uv0.z) * EXTRA_1) + ((y + ver.uv0.y) * EXTRA_2)];
        for (int i = 0; i < 18; i++) {
            if (i == counter.y) break;
            const GeneratedVertex other = MeshInput[counter.x + i];
            if (other.position.x == ver.position.x &&
                other.position.y == ver.position.y &&
                other.position.z == ver.position.z) {
                normal += other.normal;
            }
        }
    }
    normal = normalize(normal);
    
    GeneratedVertexLow low;
    low.position.x = f32tof16(ver.position.x / 1024.0) | (f32tof16(ver.position.y / 1024.0) << 16);
    low.position.y = f32tof16(ver.position.z / 1024.0) | (f32tof16(1.0) << 16);
    low.normal.x = f32tof16(normal.x) | (f32tof16(normal.y) << 16);
    low.normal.y = f32tof16(normal.z) | (f32tof16(1.0) << 16);
    low.uv0.x = f32tof16(ver.uv1.x) | (f32tof16(ver.uv1.y) << 16);
    low.uv0.y = f32tof16(ver.uv1.z) | (f32tof16(ver.uv1.w) << 16);
    low.uv1.x = f32tof16(ver.uv1.w == 0.0 ? 1.0 : 0.0) | (f32tof16(ver.uv1.w == 1.0 ? 1.0 : 0.0) << 16);
    low.uv1.y = f32tof16(ver.uv1.w == 2.0 ? 1.0 : 0.0) | (f32tof16(0.0) << 16);
    MeshVertexBuffer[index] = low;
    MeshIndexBuffer[index] = index;
}
